import { DomainsReferenceDataset } from './domains.types';

/**
 * Isolated reference data for My Domains workspace.
 *
 * NOTE:
 * - This dataset is isolated and typed.
 * - It is never stored or persisted in localStorage.
 * - Later Phase integrations will replace this reference object with an API query hook.
 */
export const DOMAINS_REFERENCE_DATA: DomainsReferenceDataset = {
  summary: {
    totalCount: 42,
    healthyCount: 34,
    healthyPercentage: 81,
    warningCount: 6,
    criticalCount: 2,
    autoRenewCount: 31,
    totalAnnualCostFormatted: '₹48,240',
  },

  domains: [
    {
      id: 'worknai-com',
      domain: 'worknai.com',
      tldBadge: '.COM',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'Cloudflare DNS',
      registrar: 'GoDaddy',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '08 Sep 2026',
      daysRemaining: 4,
      renewalCost: 1299,
      renewalCostFormatted: '₹1,299',
      autoRenew: false,
      status: 'critical',
      projectTag: 'WorknAi',
      nameservers: ['ns1.godaddy.com', 'ns2.godaddy.com'],
      sslProvider: "Let's Encrypt",
      whoisPrivacy: true,
      notes: 'This domain expires soon. Review renewal details to avoid service interruption.',
      isPrimary: true,
    },
    {
      id: 'worknai-in',
      domain: 'worknai.in',
      tldBadge: '.IN',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'Regional India Portal',
      registrar: 'GoDaddy',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '10 Sep 2026',
      daysRemaining: 6,
      renewalCost: 899,
      renewalCostFormatted: '₹899',
      autoRenew: false,
      status: 'critical',
      projectTag: 'WorknAi',
      nameservers: ['ns1.godaddy.com', 'ns2.godaddy.com'],
      sslProvider: "Let's Encrypt",
      whoisPrivacy: true,
      notes: 'Regional portal domain. Auto-renew currently set to off.',
    },
    {
      id: 'anywork-ai',
      domain: 'anywork.ai',
      tldBadge: '.AI',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'AI Orchestrator Engine',
      registrar: 'Cloudflare',
      registrarDotColor: 'bg-amber-500',
      expiryDateFormatted: '16 Sep 2026',
      daysRemaining: 12,
      renewalCost: 6850,
      renewalCostFormatted: '₹6,850',
      autoRenew: true,
      status: 'warning',
      projectTag: 'AnyWork',
      nameservers: ['dina.ns.cloudflare.com', 'todd.ns.cloudflare.com'],
      sslProvider: 'Cloudflare Universal SSL',
      whoisPrivacy: true,
      notes: 'High-value AI namespace asset. Auto-renew marked on.',
    },
    {
      id: 'aibos-cloud',
      domain: 'aibos.cloud',
      tldBadge: '.CLOUD',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'Enterprise Backend API',
      registrar: 'Hostinger',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '03 Oct 2026',
      daysRemaining: 29,
      renewalCost: 1850,
      renewalCostFormatted: '₹1,850',
      autoRenew: true,
      status: 'warning',
      projectTag: 'AI BOS',
      nameservers: ['ns1.dns-parking.com', 'ns2.dns-parking.com'],
      sslProvider: 'Hostinger SSL Lifetime',
      whoisPrivacy: true,
      notes: 'API gateway endpoints for business orchestration server.',
    },
    {
      id: 'goairclass-com',
      domain: 'goairclass.com',
      tldBadge: '.COM',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'EdTech LMS Hub',
      registrar: 'Namecheap',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '18 Jan 2027',
      daysRemaining: 136,
      renewalCost: 1199,
      renewalCostFormatted: '₹1,199',
      autoRenew: true,
      status: 'healthy',
      projectTag: 'GoAirClass',
      nameservers: ['dns1.registrar-servers.com', 'dns2.registrar-servers.com'],
      sslProvider: 'PositiveSSL Wildcard',
      whoisPrivacy: true,
      notes: 'Main education portal production namespace.',
    },
    {
      id: 'pulsecdn-net',
      domain: 'pulsecdn.net',
      tldBadge: '.NET',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'Asset Edge Router',
      registrar: 'Cloudflare',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '28 Mar 2027',
      daysRemaining: 204,
      renewalCost: 2450,
      renewalCostFormatted: '₹2,450',
      autoRenew: true,
      status: 'healthy',
      projectTag: 'Production',
      nameservers: ['dina.ns.cloudflare.com', 'todd.ns.cloudflare.com'],
      sslProvider: 'Cloudflare Edge SSL',
      whoisPrivacy: true,
      notes: 'Edge CDN proxy endpoint for domain asset delivery.',
    },
    {
      id: 'devstudio-agency',
      domain: 'devstudio.agency',
      tldBadge: '.AGENCY',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'Aman Studio Portfolio',
      registrar: 'Porkbun',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '14 Jul 2027',
      daysRemaining: 310,
      renewalCost: 3200,
      renewalCostFormatted: '₹3,200',
      autoRenew: true,
      status: 'healthy',
      projectTag: 'Client',
      nameservers: ['curitiba.ns.porkbun.com', 'fortaleza.ns.porkbun.com'],
      sslProvider: 'Let’s Encrypt',
      whoisPrivacy: true,
      notes: 'Client dev portfolio showcase and brand domain.',
    },
    {
      id: 'smartapi-io',
      domain: 'smartapi.io',
      tldBadge: '.IO',
      sslStatusText: 'SSL OK',
      dnsProviderText: 'Dev Sandbox Gateway',
      registrar: 'Cloudflare',
      registrarDotColor: 'bg-emerald-500',
      expiryDateFormatted: '15 Aug 2027',
      daysRemaining: 342,
      renewalCost: 5400,
      renewalCostFormatted: '₹5,400',
      autoRenew: true,
      status: 'healthy',
      projectTag: 'Production',
      nameservers: ['dina.ns.cloudflare.com', 'todd.ns.cloudflare.com'],
      sslProvider: 'Cloudflare Universal SSL',
      whoisPrivacy: true,
      notes: 'Development API gateway and sandbox testing endpoints.',
    },
  ],

  filterOptions: {
    statuses: ['All Statuses (42)', 'Critical (2)', 'Warning (6)', 'Healthy (34)'],
    registrars: [
      'All Registrars',
      'GoDaddy (18)',
      'Cloudflare (12)',
      'Hostinger (7)',
      'Namecheap (3)',
      'Porkbun (2)',
    ],
    tlds: ['All Extensions', '.com (26)', '.ai (8)', '.in (5)', '.org (3)'],
    autoRenewOptions: ['Auto-Renew: All', 'Enabled (31)', 'Disabled (11)'],
    tags: ['All Tags', 'WorknAi', 'AnyWork', 'AI BOS', 'GoAirClass', 'Client Production'],
    sortOptions: [
      'Expiry Soonest',
      'Expiry Latest',
      'Renewal Cost (High to Low)',
      'Renewal Cost (Low to High)',
      'Domain Name (A-Z)',
      'Recently Added',
    ],
  },
};
