import { ServerDetailData } from './serverDetails.types';

export const SERVER_DETAILS_FIXTURE_PROD_01: ServerDetailData = {
  id: 'prod-01',
  name: 'Production VPS 01',
  hostname: 'prod-vps-01',
  status: 'active',
  statusLabel: 'Inventory: Active',
  provider: 'Hostinger',
  providerAccountName: 'WorknAi Hostinger Main',
  accountEmail: 'infra@worknai.com',
  ipAddress: '103.21.58.112',
  region: 'Singapore (AP-South-1)',
  regionCode: 'SGP-1',
  osPlatform: 'Ubuntu 24.04 LTS',
  computeSpecs: '4 vCPU / 8 GB / 160 GB',
  vcpuCount: 4,
  ramGb: 8,
  storageGb: 160,
  project: 'WorknAi',
  tags: ['production', 'core-api', 'web-gateway'],
  
  specs: [
    { label: 'Compute', value: '4 vCPU', badge: 'User Added' },
    { label: 'Memory', value: '8 GB RAM', badge: 'User Added' },
    { label: 'Storage', value: '160 GB', badge: 'User Added' },
    { label: 'Operating System', value: 'Ubuntu 24.04 LTS', badge: 'User Added' },
    { label: 'Public IP', value: '103.21.58.112', badge: 'Stored Provider Data', isMono: true },
    { label: 'Region', value: 'Singapore (AP-South-1)', badge: 'Stored Provider Data' },
  ],

  relationshipNodes: [
    {
      id: 'n1',
      label: 'infra@worknai.com',
      icon: 'account_circle',
      type: 'account',
    },
    {
      id: 'n2',
      label: 'Hostinger (WorknAi Hostinger Main)',
      icon: 'cloud',
      type: 'provider',
    },
    {
      id: 'n3',
      label: 'Production VPS 01',
      icon: 'dns',
      type: 'server',
      isCurrent: true,
    },
    {
      id: 'n4',
      label: '5 Hosted Websites & Services',
      icon: 'layers',
      type: 'services',
    },
    {
      id: 'n5',
      label: '2 Connected Base Domains (worknai.com, anywork.in)',
      icon: 'link',
      type: 'domains',
    },
  ],

  hostedApps: [
    {
      id: 'app-1',
      name: 'WorknAi Website',
      domain: 'worknai.com',
      runtime: 'Next.js 14',
      port: 3000,
      reverseProxy: 'Nginx',
      sslStatusText: "SSL Retrieved • Let's Encrypt (68d remaining)",
      sslRecorded: true,
      status: 'Mapped',
    },
    {
      id: 'app-2',
      name: 'WorknAi API Gateway',
      domain: 'api.worknai.com',
      runtime: 'Node.js Express',
      port: 8080,
      reverseProxy: 'Nginx',
      sslStatusText: 'SSL Recorded',
      sslRecorded: true,
      status: 'Mapped',
    },
    {
      id: 'app-3',
      name: 'Admin Backoffice',
      domain: 'admin.worknai.com',
      runtime: 'React Vite',
      port: 4000,
      reverseProxy: 'Nginx',
      sslStatusText: 'SSL Retrieved • Cloudflare Edge',
      sslRecorded: true,
      status: 'Tracked',
    },
    {
      id: 'app-4',
      name: 'AnyWork Landing App',
      domain: 'anywork.in',
      runtime: 'Next.js',
      port: 3001,
      reverseProxy: 'Nginx',
      sslStatusText: "SSL Retrieved • Let's Encrypt (68d remaining)",
      sslRecorded: true,
      status: 'Mapped',
    },
    {
      id: 'app-5',
      name: 'AnyWork Microservice',
      domain: 'api.anywork.in',
      runtime: 'Node.js',
      port: 8081,
      reverseProxy: 'Nginx',
      sslStatusText: 'SSL Recorded',
      sslRecorded: true,
      status: 'Mapped',
    },
  ],

  dnsMappings: [
    {
      id: 'dns-1',
      hostname: 'worknai.com',
      recordType: 'A Record',
      provenance: 'DNS Retrieved',
      target: '103.21.58.112',
      dnsProvider: 'DNS: Cloudflare',
    },
    {
      id: 'dns-2',
      hostname: 'api.worknai.com',
      recordType: 'CNAME',
      provenance: 'DNS Retrieved',
      target: 'prod-vps-01.worknai.com',
      dnsProvider: 'DNS: Cloudflare',
    },
    {
      id: 'dns-3',
      hostname: 'admin.worknai.com',
      recordType: 'A Record',
      provenance: 'DNS Retrieved',
      target: '103.21.58.112',
      dnsProvider: 'DNS: Cloudflare',
    },
    {
      id: 'dns-4',
      hostname: 'anywork.in',
      recordType: 'A Record',
      provenance: 'User Mapped',
      target: '103.21.58.112',
      dnsProvider: 'DNS: GoDaddy DNS',
    },
    {
      id: 'dns-5',
      hostname: 'api.anywork.in',
      recordType: 'CNAME',
      provenance: 'User Mapped',
      target: 'anywork.in',
      dnsProvider: 'DNS: GoDaddy DNS',
    },
  ],

  billing: {
    accountName: 'WorknAi Hostinger Main',
    accountEmail: 'infra@worknai.com',
    monthlyCostFormatted: '₹1,499',
    annualizedCostFormatted: '₹17,988',
    renewalDateFormatted: '18 Oct 2026',
    billingFrequency: 'Monthly',
    autoRenew: true,
    notificationEmail: 'infra@worknai.com',
    notificationLeadDays: 14,
  },

  notes: 'Primary production API & SSR rendering node for WorknAi and AnyWork web properties.',
};

export const SERVER_DETAILS_FIXTURE_AIBOS: ServerDetailData = {
  id: 'aibos',
  name: 'AI BOS Server',
  hostname: 'aibos-sgp-core',
  status: 'active',
  statusLabel: 'Inventory: Active',
  provider: 'DigitalOcean',
  providerAccountName: 'WorknAi DigitalOcean Fleet',
  accountEmail: 'servers@worknai.com',
  ipAddress: '159.89.162.40',
  region: 'Bangalore (BLR-1)',
  regionCode: 'BLR-1',
  osPlatform: 'Ubuntu 22.04 LTS',
  computeSpecs: '4 vCPU / 8 GB / 160 GB',
  vcpuCount: 4,
  ramGb: 8,
  storageGb: 160,
  project: 'AI BOS',
  tags: ['ai-runtime', 'agent-core', 'gpu-orchestrator'],
  specs: [
    { label: 'Compute', value: '4 vCPU', badge: 'User Added' },
    { label: 'Memory', value: '8 GB RAM', badge: 'User Added' },
    { label: 'Storage', value: '160 GB', badge: 'User Added' },
    { label: 'Operating System', value: 'Ubuntu 22.04 LTS', badge: 'User Added' },
    { label: 'Public IP', value: '159.89.162.40', badge: 'Stored Provider Data', isMono: true },
    { label: 'Region', value: 'Bangalore (BLR-1)', badge: 'Stored Provider Data' },
  ],
  relationshipNodes: [
    { id: 'n1', label: 'servers@worknai.com', icon: 'account_circle', type: 'account' },
    { id: 'n2', label: 'DigitalOcean (WorknAi DigitalOcean Fleet)', icon: 'cloud', type: 'provider' },
    { id: 'n3', label: 'AI BOS Server', icon: 'dns', type: 'server', isCurrent: true },
    { id: 'n4', label: '3 Hosted Websites & Services', icon: 'layers', type: 'services' },
    { id: 'n5', label: '1 Connected Base Domain (aibos.cloud)', icon: 'link', type: 'domains' },
  ],
  hostedApps: [
    {
      id: 'app-6',
      name: 'AI BOS Core Engine',
      domain: 'aibos.cloud',
      runtime: 'FastAPI Python 3.11',
      port: 8000,
      reverseProxy: 'Caddy',
      sslStatusText: 'SSL Recorded • Let\'s Encrypt',
      sslRecorded: true,
      status: 'Mapped',
    },
    {
      id: 'app-7',
      name: 'AI BOS App Portal',
      domain: 'app.aibos.cloud',
      runtime: 'Next.js 14',
      port: 3000,
      reverseProxy: 'Caddy',
      sslStatusText: 'SSL Recorded • Cloudflare Edge',
      sslRecorded: true,
      status: 'Mapped',
    },
    {
      id: 'app-8',
      name: 'Worker Orchestrator',
      domain: 'orchestrator.aibos.internal',
      runtime: 'Node.js Worker',
      port: 9090,
      reverseProxy: 'Internal Only',
      sslStatusText: 'SSL Recorded • Internal CA',
      sslRecorded: true,
      status: 'Tracked',
    },
  ],
  dnsMappings: [
    {
      id: 'dns-6',
      hostname: 'aibos.cloud',
      recordType: 'A Record',
      provenance: 'DNS Retrieved',
      target: '159.89.162.40',
      dnsProvider: 'DNS: Cloudflare',
    },
    {
      id: 'dns-7',
      hostname: 'app.aibos.cloud',
      recordType: 'CNAME',
      provenance: 'DNS Retrieved',
      target: 'aibos.cloud',
      dnsProvider: 'DNS: Cloudflare',
    },
  ],
  billing: {
    accountName: 'WorknAi DigitalOcean Fleet',
    accountEmail: 'servers@worknai.com',
    monthlyCostFormatted: '₹2,100',
    annualizedCostFormatted: '₹25,200',
    renewalDateFormatted: '28 Nov 2026',
    billingFrequency: 'Monthly',
    autoRenew: true,
    notificationEmail: 'servers@worknai.com',
    notificationLeadDays: 14,
  },
  notes: 'AI orchestration and agent runtime core compute cluster.',
};

export const SERVER_DETAILS_DATABASE: Record<string, ServerDetailData> = {
  'prod-01': SERVER_DETAILS_FIXTURE_PROD_01,
  'aibos': SERVER_DETAILS_FIXTURE_AIBOS,
};

export function getServerDetail(serverId?: string): ServerDetailData {
  if (serverId && SERVER_DETAILS_DATABASE[serverId]) {
    return SERVER_DETAILS_DATABASE[serverId];
  }
  return SERVER_DETAILS_FIXTURE_PROD_01;
}
