import { ServersReferenceDataset } from './servers.types';

export const SERVERS_REFERENCE_DATA: ServersReferenceDataset = {
  summary: {
    totalServers: 6,
    activeCount: 5,
    attentionCount: 1,
    hostedWebsitesCount: 18,
    totalMonthlyCost: 8450,
    totalMonthlyCostFormatted: '₹8,450',
    upcomingRenewalsCount: 2,
    upcomingRenewalsSubtext: 'Next: 7 & 14 days',
  },

  servers: [
    {
      id: 'prod-01',
      name: 'Production VPS 01',
      hostname: 'prod-vps-01',
      provider: 'Hostinger',
      providerColor: {
        bg: 'bg-[#673de6]/10',
        text: 'text-[#4c1d95]',
        dot: 'bg-[#673de6]',
      },
      accountName: 'WorknAi Hostinger Main',
      accountEmail: 'infra@worknai.com',
      ipAddress: '103.21.58.112',
      region: 'Singapore',
      regionCode: 'SGP-1',
      osPlatform: 'Ubuntu 24.04 LTS',
      computeSpecs: '4 vCPU / 8 GB / 160 GB',
      vcpuCount: 4,
      ramGb: 8,
      storageGb: 160,
      storageType: 'NVMe SSD',
      storageProgressPercentage: 46,
      hostedWebsitesCount: 5,
      monthlyCost: 1499,
      monthlyCostFormatted: '₹1,499',
      annualizedRunRateFormatted: '₹17,988/yr',
      renewalDateFormatted: '18 Oct 2026',
      autoRenew: true,
      status: 'active',
      statusLabel: 'Inventory: Active',
      connectedWebsites: [
        { id: 'w1', domain: 'worknai.com', tag: 'Production', sslAvailable: true },
        { id: 'w2', domain: 'api.worknai.com', tag: 'API Gateway', sslAvailable: true },
        { id: 'w3', domain: 'admin.worknai.com', tag: 'Backoffice', sslAvailable: true },
        { id: 'w4', domain: 'anywork.in', tag: 'Production', sslAvailable: true },
        { id: 'w5', domain: 'api.anywork.in', tag: 'Backend', sslAvailable: true },
      ],
      notes: 'Primary production API & SSR rendering node for WorknAi and AnyWork.',
    },
    {
      id: 'aibos',
      name: 'AI BOS Server',
      hostname: 'aibos-sgp-core',
      provider: 'DigitalOcean',
      providerColor: {
        bg: 'bg-[#0080FF]/10',
        text: 'text-[#0060df]',
        dot: 'bg-[#0080FF]',
      },
      accountName: 'WorknAi DigitalOcean Fleet',
      accountEmail: 'servers@worknai.com',
      ipAddress: '159.89.162.40',
      region: 'Bangalore',
      regionCode: 'BLR-1',
      osPlatform: 'Ubuntu 22.04 LTS',
      computeSpecs: '4 vCPU / 8 GB / 160 GB',
      vcpuCount: 4,
      ramGb: 8,
      storageGb: 160,
      storageType: 'NVMe SSD',
      storageProgressPercentage: 62,
      hostedWebsitesCount: 3,
      monthlyCost: 2100,
      monthlyCostFormatted: '₹2,100',
      annualizedRunRateFormatted: '₹25,200/yr',
      renewalDateFormatted: '28 Nov 2026',
      autoRenew: true,
      status: 'active',
      statusLabel: 'Inventory: Active',
      connectedWebsites: [
        { id: 'w6', domain: 'aibos.cloud', tag: 'Core Engine', sslAvailable: true },
        { id: 'w7', domain: 'app.aibos.cloud', tag: 'Frontend', sslAvailable: true },
        { id: 'w8', domain: 'orchestrator.aibos.internal', tag: 'Worker API', sslAvailable: true },
      ],
      notes: 'AI orchestration and agent runtime core compute cluster.',
    },
    {
      id: 'legacy',
      name: 'Legacy VPS',
      hostname: 'vultr-legacy-srv',
      provider: 'Vultr',
      providerColor: {
        bg: 'bg-[#007bfc]/10',
        text: 'text-[#0051a8]',
        dot: 'bg-[#007bfc]',
      },
      accountName: 'Aman Personal Cloud',
      accountEmail: 'aman@gmail.com',
      ipAddress: '45.76.180.25',
      region: 'Mumbai',
      regionCode: 'BOM-1',
      osPlatform: 'Debian 12',
      computeSpecs: '2 vCPU / 4 GB / 80 GB',
      vcpuCount: 2,
      ramGb: 4,
      storageGb: 80,
      storageType: 'SSD',
      storageProgressPercentage: 78,
      hostedWebsitesCount: 1,
      monthlyCost: 950,
      monthlyCostFormatted: '₹950',
      annualizedRunRateFormatted: '₹11,400/yr',
      renewalDateFormatted: '12 Sep 2026',
      renewalDaysRemaining: 7,
      autoRenew: false,
      status: 'attention',
      statusLabel: 'Needs Attention',
      connectedWebsites: [
        { id: 'w9', domain: 'devstudio.agency', tag: 'Showcase', sslAvailable: true },
      ],
      notes: 'Expiring in 7 days. Auto-renew disabled at user level.',
    },
    {
      id: 'staging',
      name: 'AnyWork Staging Node',
      hostname: 'anywork-stg-01',
      provider: 'Hostinger',
      providerColor: {
        bg: 'bg-[#673de6]/10',
        text: 'text-[#4c1d95]',
        dot: 'bg-[#673de6]',
      },
      accountName: 'WorknAi Hostinger Main',
      accountEmail: 'infra@worknai.com',
      ipAddress: '103.21.59.84',
      region: 'Singapore',
      regionCode: 'SGP-1',
      osPlatform: 'Ubuntu 24.04 LTS',
      computeSpecs: '2 vCPU / 4 GB / 100 GB',
      vcpuCount: 2,
      ramGb: 4,
      storageGb: 100,
      storageType: 'NVMe SSD',
      storageProgressPercentage: 35,
      hostedWebsitesCount: 4,
      monthlyCost: 899,
      monthlyCostFormatted: '₹899',
      annualizedRunRateFormatted: '₹10,788/yr',
      renewalDateFormatted: '12 Feb 2027',
      autoRenew: true,
      status: 'active',
      statusLabel: 'Inventory: Active',
      connectedWebsites: [
        { id: 'w10', domain: 'stg.anywork.ai', tag: 'Staging Web', sslAvailable: true },
        { id: 'w11', domain: 'stg-api.anywork.ai', tag: 'Staging API', sslAvailable: true },
        { id: 'w12', domain: 'preview.worknai.com', tag: 'Preview Env', sslAvailable: true },
        { id: 'w13', domain: 'docs-dev.worknai.com', tag: 'Dev Docs', sslAvailable: true },
      ],
      notes: 'Staging and PR review deployments.',
    },
    {
      id: 'analytics',
      name: 'Analytics Worker',
      hostname: 'do-blr-worker',
      provider: 'DigitalOcean',
      providerColor: {
        bg: 'bg-[#0080FF]/10',
        text: 'text-[#0060df]',
        dot: 'bg-[#0080FF]',
      },
      accountName: 'WorknAi DigitalOcean Fleet',
      accountEmail: 'servers@worknai.com',
      ipAddress: '139.59.34.19',
      region: 'Bangalore',
      regionCode: 'BLR-1',
      osPlatform: 'Ubuntu 22.04 LTS',
      computeSpecs: '2 vCPU / 4 GB / 80 GB',
      vcpuCount: 2,
      ramGb: 4,
      storageGb: 80,
      storageType: 'NVMe SSD',
      storageProgressPercentage: 54,
      hostedWebsitesCount: 3,
      monthlyCost: 1450,
      monthlyCostFormatted: '₹1,450',
      annualizedRunRateFormatted: '₹17,400/yr',
      renewalDateFormatted: '15 Nov 2026',
      autoRenew: true,
      status: 'active',
      statusLabel: 'Inventory: Active',
      connectedWebsites: [
        { id: 'w14', domain: 'pulsecdn.net', tag: 'Telemetry Proxy', sslAvailable: true },
        { id: 'w15', domain: 'metrics.worknai.com', tag: 'Grafana Stack', sslAvailable: true },
        { id: 'w16', domain: 'logs.worknai.internal', tag: 'Log Engine', sslAvailable: true },
      ],
      notes: 'Log ingestion and metrics processing instance.',
    },
    {
      id: 'hetzner',
      name: 'Backup Storage Box',
      hostname: 'storage-fra-01',
      provider: 'Hetzner',
      providerColor: {
        bg: 'bg-[#d50c2d]/10',
        text: 'text-[#a3001c]',
        dot: 'bg-[#d50c2d]',
      },
      accountName: 'WorknAi Infrastructure Hetzner',
      accountEmail: 'infra@worknai.com',
      ipAddress: '168.119.82.10',
      region: 'Frankfurt',
      regionCode: 'FRA-1',
      osPlatform: 'Debian 12',
      computeSpecs: '2 vCPU / 2 GB / 1 TB HDD',
      vcpuCount: 2,
      ramGb: 2,
      storageGb: 1024,
      storageType: 'SATA Enterprise HDD',
      storageProgressPercentage: 42,
      hostedWebsitesCount: 2,
      monthlyCost: 1552,
      monthlyCostFormatted: '₹1,552',
      annualizedRunRateFormatted: '₹18,624/yr',
      renewalDateFormatted: '04 Jan 2027',
      autoRenew: true,
      status: 'active',
      statusLabel: 'Inventory: Active',
      connectedWebsites: [
        { id: 'w17', domain: 'backups.worknai.internal', tag: 'Cold Snapshot Vault', sslAvailable: true },
        { id: 'w18', domain: 'archive.worknai.com', tag: 'Audit Storage', sslAvailable: true },
      ],
      notes: 'Off-site backup repository and archival disk array.',
    },
  ],

  filterOptions: {
    providers: ['Provider: All', 'Hostinger', 'DigitalOcean', 'Vultr', 'Hetzner'],
    regions: ['Region: Global', 'Singapore', 'Bangalore', 'Mumbai', 'Frankfurt'],
    accountEmails: ['All Accounts', 'infra@worknai.com', 'servers@worknai.com', 'aman@gmail.com'],
    osList: ['All OS', 'Ubuntu 24.04 LTS', 'Ubuntu 22.04 LTS', 'Debian 12'],
    sortOptions: [
      'Renewal Soonest',
      'Monthly Cost (High to Low)',
      'Server Name (A-Z)',
      'Websites Count',
    ],
  },
};
