import {
  InfrastructureNode,
  InfrastructureEdge,
  GraphSummaryMetrics,
} from './infrastructureMap.types';

export const INITIAL_GRAPH_NODES: InfrastructureNode[] = [
  // ==========================================
  // CHAIN 1: WorknAi Production Chain
  // ==========================================
  {
    id: 'email-domains',
    nodeType: 'email',
    label: 'domains@worknai.com',
    title: 'domains@worknai.com',
    subtext: 'Registration Account',
    categoryLabel: 'EMAIL',
    categoryColor: 'bg-purple-100',
    badgeTextColor: 'text-purple-800',
    dotColor: 'bg-purple-600',
    x: 30,
    y: 95,
    width: 160,
    metadata: {
      accountOwnerEmail: 'domains@worknai.com',
      statusText: 'User Mapped • Stored Record',
      associatedDomains: ['worknai.com', 'anywork.in'],
      targetRoute: '/accounts',
      notes: 'Registered corporate domain owner address.',
    },
  },
  {
    id: 'prov-godaddy',
    nodeType: 'provider',
    label: 'GoDaddy Main',
    title: 'GoDaddy Main',
    subtext: '14 mapped domains',
    categoryLabel: 'PROVIDER ACCOUNT',
    categoryColor: 'bg-indigo-100',
    badgeTextColor: 'text-indigo-800',
    dotColor: 'bg-indigo-600',
    x: 280,
    y: 95,
    width: 170,
    metadata: {
      providerCompany: 'GoDaddy LLC',
      accountOwnerEmail: 'domains@worknai.com',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'email-domains',
      upstreamNodeLabel: 'domains@worknai.com',
      associatedDomains: ['worknai.com', 'clientportal.com'],
      targetRoute: '/accounts/godaddy-main',
    },
  },
  {
    id: 'dom-worknai',
    nodeType: 'domain',
    label: 'worknai.com',
    title: 'worknai.com',
    subtext: 'Auto-Renew: User Mapped On',
    categoryLabel: 'Apex Domain',
    categoryColor: 'bg-sky-100',
    badgeTextColor: 'text-sky-800',
    dotColor: 'bg-sky-600',
    x: 540,
    y: 95,
    width: 170,
    metadata: {
      providerCompany: 'GoDaddy LLC',
      statusText: 'Stored Record • Active',
      upstreamNodeId: 'prov-godaddy',
      upstreamNodeLabel: 'GoDaddy Main',
      associatedDomains: ['worknai.com'],
      associatedProjects: ['WorknAi Enterprise'],
      targetRoute: '/domains/worknai.com',
    },
  },
  {
    id: 'email-infra',
    nodeType: 'email',
    label: 'infra@worknai.com',
    title: 'infra@worknai.com',
    subtext: 'Infrastructure Account',
    categoryLabel: 'EMAIL',
    categoryColor: 'bg-purple-100',
    badgeTextColor: 'text-purple-800',
    dotColor: 'bg-purple-600',
    x: 30,
    y: 205,
    width: 160,
    metadata: {
      accountOwnerEmail: 'infra@worknai.com',
      statusText: 'User Mapped • Stored Record',
      associatedDomains: ['worknai.com', 'businesshub.in'],
      targetRoute: '/accounts',
      notes: 'Manages Hostinger and Cloudflare administrative accounts.',
    },
  },
  {
    id: 'prov-hostinger',
    nodeType: 'provider',
    label: 'Hostinger Main',
    title: 'Hostinger Main',
    subtext: 'WorknAi Portfolio',
    categoryLabel: 'PROVIDER ACCOUNT',
    categoryColor: 'bg-indigo-100',
    badgeTextColor: 'text-indigo-800',
    dotColor: 'bg-indigo-600',
    x: 280,
    y: 205,
    width: 170,
    metadata: {
      providerCompany: 'Hostinger International',
      accountOwnerEmail: 'infra@worknai.com',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'email-infra',
      upstreamNodeLabel: 'infra@worknai.com',
      associatedDomains: ['businesshub.in', 'worknflow.co.in'],
      targetRoute: '/accounts/hostinger-main',
    },
  },
  {
    id: 'server-vps01',
    nodeType: 'server',
    label: 'Production VPS 01',
    title: 'Production VPS 01',
    subtext: '103.21.58.112',
    categoryLabel: 'VPS / Server',
    categoryColor: 'bg-amber-100',
    badgeTextColor: 'text-amber-800',
    dotColor: 'bg-amber-600',
    x: 540,
    y: 200,
    width: 180,
    metadata: {
      isPrimaryNode: true,
      providerCompany: 'Hostinger',
      accountOwnerEmail: 'infra@worknai.com',
      ipAddress: '103.21.58.112',
      specs: '4 vCPU · 8 GB RAM',
      storage: '160 GB NVMe SSD',
      monthlyCost: 'Est. ₹1,499/mo',
      region: 'Singapore (SIN-01)',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'prov-hostinger',
      upstreamNodeLabel: 'Hostinger Main',
      upstreamNodeSubtext: 'via infra@worknai.com',
      downstreamItems: [
        {
          id: 'ds-1',
          title: 'WorknAi Website',
          subtext: 'worknai.com',
          port: 'Port 3000',
          color: 'bg-emerald-500',
        },
        {
          id: 'ds-2',
          title: 'WorknAi API',
          subtext: 'api.worknai.com',
          port: 'Port 8080',
          color: 'bg-emerald-500',
        },
        {
          id: 'ds-3',
          title: 'AI BOS Admin',
          subtext: 'admin.worknai.com',
          port: 'Port 4200',
          color: 'bg-emerald-500',
        },
        {
          id: 'ds-4',
          title: 'AnyWork Landing',
          subtext: 'anywork.in',
          port: 'Port 3001',
          color: 'bg-emerald-500',
        },
        {
          id: 'ds-5',
          title: 'AnyWork API',
          subtext: 'api.anywork.in',
          port: 'Port 5000',
          color: 'bg-emerald-500',
        },
      ],
      associatedDomains: ['worknai.com', 'anywork.in'],
      associatedProjects: ['WorknAi Enterprise', 'AnyWork Suite'],
      targetRoute: '/servers/prod-01',
      notes: 'Main compute cluster hosting primary production services.',
    },
  },
  {
    id: 'web-worknai',
    nodeType: 'website',
    label: 'WorknAi Website',
    title: 'WorknAi Website',
    subtext: 'worknai.com',
    categoryLabel: 'Website App',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 820,
    y: 165,
    width: 170,
    metadata: {
      framework: 'Next.js 14 SSR',
      port: 'Port 3000',
      ipAddress: '103.21.58.112',
      upstreamNodeId: 'server-vps01',
      upstreamNodeLabel: 'Production VPS 01',
      associatedDomains: ['worknai.com'],
      associatedProjects: ['WorknAi Enterprise'],
      targetRoute: '/websites/worknai-website',
    },
  },
  {
    id: 'web-worknai-api',
    nodeType: 'website',
    label: 'WorknAi API',
    title: 'WorknAi API',
    subtext: 'Node.js Express',
    categoryLabel: 'API Backend',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 820,
    y: 255,
    width: 170,
    metadata: {
      framework: 'Express TypeScript',
      port: 'Port 8080',
      ipAddress: '103.21.58.112',
      upstreamNodeId: 'server-vps01',
      upstreamNodeLabel: 'Production VPS 01',
      associatedDomains: ['worknai.com'],
      associatedProjects: ['WorknAi Enterprise'],
      targetRoute: '/websites/worknai-website',
    },
  },
  {
    id: 'dom-api-worknai',
    nodeType: 'domain',
    label: 'api.worknai.com',
    title: 'api.worknai.com',
    subtext: 'SSL Secured',
    categoryLabel: 'Subdomain (A)',
    categoryColor: 'bg-sky-100',
    badgeTextColor: 'text-sky-800',
    dotColor: 'bg-sky-600',
    x: 1090,
    y: 255,
    width: 170,
    metadata: {
      providerCompany: 'Cloudflare DNS',
      statusText: 'A Record → 103.21.58.112',
      upstreamNodeId: 'web-worknai-api',
      upstreamNodeLabel: 'WorknAi API',
      associatedDomains: ['worknai.com'],
      targetRoute: '/domains/worknai.com',
    },
  },

  // ==========================================
  // CHAIN 2: AnyWork Suite Chain
  // ==========================================
  {
    id: 'dom-anywork',
    nodeType: 'domain',
    label: 'anywork.in',
    title: 'anywork.in',
    subtext: 'via domains@worknai.com',
    categoryLabel: 'Apex Domain',
    categoryColor: 'bg-sky-100',
    badgeTextColor: 'text-sky-800',
    dotColor: 'bg-sky-600',
    x: 280,
    y: 355,
    width: 170,
    metadata: {
      providerCompany: 'Namecheap',
      accountOwnerEmail: 'domains@worknai.com',
      statusText: 'DNS Record • Stored',
      associatedDomains: ['anywork.in'],
      associatedProjects: ['AnyWork Suite'],
      targetRoute: '/domains/anywork.ai',
    },
  },
  {
    id: 'web-anywork-landing',
    nodeType: 'website',
    label: 'AnyWork Landing',
    title: 'AnyWork Landing',
    subtext: 'Next.js App',
    categoryLabel: 'Landing Page',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 560,
    y: 355,
    width: 170,
    metadata: {
      framework: 'Next.js static export',
      port: 'Port 3001',
      ipAddress: '103.21.58.112',
      upstreamNodeId: 'server-vps01',
      upstreamNodeLabel: 'Production VPS 01',
      associatedDomains: ['anywork.in'],
      associatedProjects: ['AnyWork Suite'],
      targetRoute: '/websites/worknai-website',
    },
  },

  // ==========================================
  // CHAIN 3: DigitalOcean AI BOS Chain
  // ==========================================
  {
    id: 'email-servers',
    nodeType: 'email',
    label: 'servers@worknai.com',
    title: 'servers@worknai.com',
    subtext: 'Server Account',
    categoryLabel: 'EMAIL',
    categoryColor: 'bg-purple-100',
    badgeTextColor: 'text-purple-800',
    dotColor: 'bg-purple-600',
    x: 30,
    y: 465,
    width: 160,
    metadata: {
      accountOwnerEmail: 'servers@worknai.com',
      statusText: 'Team Infrastructure Account',
      associatedDomains: ['aibos.ai'],
      targetRoute: '/accounts',
    },
  },
  {
    id: 'prov-do',
    nodeType: 'provider',
    label: 'Team WorknAi DO',
    title: 'Team WorknAi DO',
    subtext: 'DigitalOcean Team',
    categoryLabel: 'PROVIDER ACCOUNT',
    categoryColor: 'bg-indigo-100',
    badgeTextColor: 'text-indigo-800',
    dotColor: 'bg-indigo-600',
    x: 280,
    y: 465,
    width: 170,
    metadata: {
      providerCompany: 'DigitalOcean Inc.',
      accountOwnerEmail: 'servers@worknai.com',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'email-servers',
      upstreamNodeLabel: 'servers@worknai.com',
      targetRoute: '/accounts/digitalocean-team',
    },
  },
  {
    id: 'server-aibos',
    nodeType: 'server',
    label: 'AI BOS Server',
    title: 'AI BOS Server',
    subtext: '159.89.172.94',
    categoryLabel: 'VPS / Server',
    categoryColor: 'bg-amber-100',
    badgeTextColor: 'text-amber-800',
    dotColor: 'bg-amber-600',
    x: 540,
    y: 465,
    width: 170,
    metadata: {
      providerCompany: 'DigitalOcean',
      accountOwnerEmail: 'servers@worknai.com',
      ipAddress: '159.89.172.94',
      specs: '4 vCPU · 8 GB RAM',
      storage: '160 GB NVMe SSD',
      monthlyCost: 'Est. ₹2,100/mo',
      region: 'Bangalore (BLR-1)',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'prov-do',
      upstreamNodeLabel: 'Team WorknAi DO',
      associatedDomains: ['admin.worknai.com'],
      associatedProjects: ['AI BOS Platform'],
      targetRoute: '/servers/aibos',
    },
  },
  {
    id: 'web-aibos-admin',
    nodeType: 'website',
    label: 'AI BOS Admin',
    title: 'AI BOS Admin',
    subtext: 'Admin Dashboard',
    categoryLabel: 'Internal WebApp',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 820,
    y: 465,
    width: 170,
    metadata: {
      framework: 'React Vite SPA',
      port: 'Port 4000',
      ipAddress: '159.89.172.94',
      upstreamNodeId: 'server-aibos',
      upstreamNodeLabel: 'AI BOS Server',
      associatedDomains: ['admin.worknai.com'],
      associatedProjects: ['AI BOS Platform'],
      targetRoute: '/websites/web-3',
    },
  },
  {
    id: 'dom-admin-worknai',
    nodeType: 'domain',
    label: 'admin.worknai.com',
    title: 'admin.worknai.com',
    subtext: 'Cloudflare Proxy',
    categoryLabel: 'Subdomain (CNAME)',
    categoryColor: 'bg-sky-100',
    badgeTextColor: 'text-sky-800',
    dotColor: 'bg-sky-600',
    x: 1090,
    y: 465,
    width: 170,
    metadata: {
      providerCompany: 'Cloudflare DNS',
      statusText: 'DNS Record (CNAME)',
      upstreamNodeId: 'web-aibos-admin',
      upstreamNodeLabel: 'AI BOS Admin',
      associatedDomains: ['worknai.com'],
      targetRoute: '/domains/worknai.com',
    },
  },

  // ==========================================
  // CHAIN 4: Legacy Personal Chain
  // ==========================================
  {
    id: 'email-aman',
    nodeType: 'email',
    label: 'aman@gmail.com',
    title: 'aman@gmail.com',
    subtext: 'Personal Account',
    categoryLabel: 'EMAIL',
    categoryColor: 'bg-purple-100',
    badgeTextColor: 'text-purple-800',
    dotColor: 'bg-purple-600',
    x: 30,
    y: 595,
    width: 160,
    metadata: {
      accountOwnerEmail: 'aman@gmail.com',
      statusText: 'Personal Account Email',
      targetRoute: '/accounts',
    },
  },
  {
    id: 'prov-vultr',
    nodeType: 'provider',
    label: 'Vultr Personal',
    title: 'Vultr Personal',
    subtext: '1 Instance',
    categoryLabel: 'PROVIDER ACCOUNT',
    categoryColor: 'bg-indigo-100',
    badgeTextColor: 'text-indigo-800',
    dotColor: 'bg-indigo-600',
    x: 280,
    y: 595,
    width: 170,
    metadata: {
      providerCompany: 'Vultr Cloud',
      accountOwnerEmail: 'aman@gmail.com',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'email-aman',
      upstreamNodeLabel: 'aman@gmail.com',
      targetRoute: '/accounts',
    },
  },
  {
    id: 'server-legacy',
    nodeType: 'server',
    label: 'Legacy VPS',
    title: 'Legacy VPS',
    subtext: '45.76.182.201',
    categoryLabel: 'VPS / Server',
    categoryColor: 'bg-amber-100',
    badgeTextColor: 'text-amber-800',
    dotColor: 'bg-amber-600',
    x: 540,
    y: 595,
    width: 170,
    metadata: {
      providerCompany: 'Vultr',
      accountOwnerEmail: 'aman@gmail.com',
      ipAddress: '45.76.182.201',
      specs: '1 vCPU · 2 GB RAM',
      storage: '40 GB SSD',
      monthlyCost: 'Est. ₹600/mo',
      region: 'Tokyo (NRT-01)',
      statusText: 'Mapped Record • Inventory',
      upstreamNodeId: 'prov-vultr',
      upstreamNodeLabel: 'Vultr Personal',
      associatedProjects: ['Legacy Client Services'],
      targetRoute: '/servers/legacy',
    },
  },
  {
    id: 'web-legacy-blog',
    nodeType: 'website',
    label: 'Legacy Client Blog',
    title: 'Legacy Client Blog',
    subtext: 'Pending Migration',
    categoryLabel: 'WordPress Site',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 820,
    y: 595,
    width: 170,
    metadata: {
      framework: 'WordPress PHP 8.1',
      ipAddress: '45.76.182.201',
      upstreamNodeId: 'server-legacy',
      upstreamNodeLabel: 'Legacy VPS',
      associatedProjects: ['Legacy Client Services'],
      targetRoute: '/websites',
    },
  },

  // ==========================================
  // PROJECT NODES
  // ==========================================
  {
    id: 'proj-worknai',
    nodeType: 'project',
    label: 'WorknAi Enterprise',
    title: 'WorknAi Enterprise',
    subtext: 'Core Platform Project',
    categoryLabel: 'PROJECT',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 1350,
    y: 165,
    width: 170,
    metadata: {
      statusText: 'Stored Record • Project',
      associatedDomains: ['worknai.com', 'api.worknai.com'],
      targetRoute: '/overview',
      notes: 'Core enterprise multi-service web platform project.',
    },
  },
  {
    id: 'proj-anywork',
    nodeType: 'project',
    label: 'AnyWork Suite',
    title: 'AnyWork Suite',
    subtext: 'Client Solution Project',
    categoryLabel: 'PROJECT',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 820,
    y: 355,
    width: 170,
    metadata: {
      statusText: 'Stored Record • Project',
      associatedDomains: ['anywork.in'],
      targetRoute: '/overview',
      notes: 'AnyWork client services suite.',
    },
  },
  {
    id: 'proj-aibos',
    nodeType: 'project',
    label: 'AI BOS Platform',
    title: 'AI BOS Platform',
    subtext: 'Agent Runtime Project',
    categoryLabel: 'PROJECT',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 1350,
    y: 465,
    width: 170,
    metadata: {
      statusText: 'Stored Record • Project',
      associatedDomains: ['admin.worknai.com'],
      targetRoute: '/overview',
      notes: 'AI orchestration and agent runtime core compute cluster.',
    },
  },
  {
    id: 'proj-legacy',
    nodeType: 'project',
    label: 'Legacy Client Services',
    title: 'Legacy Client Services',
    subtext: 'Archived Portfolio Project',
    categoryLabel: 'PROJECT',
    categoryColor: 'bg-emerald-100',
    badgeTextColor: 'text-emerald-800',
    dotColor: 'bg-emerald-600',
    x: 1090,
    y: 595,
    width: 170,
    metadata: {
      statusText: 'Stored Record • Project',
      targetRoute: '/overview',
      notes: 'Archived legacy client sites and blogs.',
    },
  },
];

export const INITIAL_GRAPH_EDGES: InfrastructureEdge[] = [
  // Chain 1: Production
  {
    id: 'edge-1',
    sourceNodeId: 'email-domains',
    targetNodeId: 'prov-godaddy',
    relationshipType: 'owns',
    path: 'M 190 125 C 235 125, 235 125, 280 125',
    isActive: true,
  },
  {
    id: 'edge-2',
    sourceNodeId: 'prov-godaddy',
    targetNodeId: 'dom-worknai',
    relationshipType: 'manages',
    path: 'M 450 125 C 495 125, 495 125, 540 125',
    isActive: true,
  },
  {
    id: 'edge-3',
    sourceNodeId: 'dom-worknai',
    targetNodeId: 'web-worknai',
    relationshipType: 'resolves_to',
    path: 'M 710 125 C 765 125, 765 195, 820 195',
    isActive: true,
  },
  {
    id: 'edge-4',
    sourceNodeId: 'email-infra',
    targetNodeId: 'prov-hostinger',
    relationshipType: 'owns',
    path: 'M 190 235 C 235 235, 235 235, 280 235',
    isActive: true,
  },
  {
    id: 'edge-5',
    sourceNodeId: 'prov-hostinger',
    targetNodeId: 'server-vps01',
    relationshipType: 'hosts',
    path: 'M 450 235 C 495 235, 495 235, 540 235',
    isActive: true,
  },
  {
    id: 'edge-6',
    sourceNodeId: 'server-vps01',
    targetNodeId: 'web-worknai',
    relationshipType: 'hosts',
    path: 'M 720 235 C 770 235, 770 195, 820 195',
    isActive: true,
  },
  {
    id: 'edge-7',
    sourceNodeId: 'server-vps01',
    targetNodeId: 'web-worknai-api',
    relationshipType: 'hosts',
    path: 'M 720 235 C 770 235, 770 285, 820 285',
    isActive: true,
  },
  {
    id: 'edge-8',
    sourceNodeId: 'web-worknai-api',
    targetNodeId: 'dom-api-worknai',
    relationshipType: 'resolves_to',
    path: 'M 990 285 C 1040 285, 1040 285, 1090 285',
    isActive: true,
  },
  {
    id: 'edge-proj-1',
    sourceNodeId: 'web-worknai',
    targetNodeId: 'proj-worknai',
    relationshipType: 'attached_to',
    path: 'M 990 195 C 1170 195, 1170 195, 1350 195',
    isActive: true,
  },
  {
    id: 'edge-proj-2',
    sourceNodeId: 'dom-api-worknai',
    targetNodeId: 'proj-worknai',
    relationshipType: 'attached_to',
    path: 'M 1260 285 C 1305 285, 1305 195, 1350 195',
    isActive: true,
  },

  // Chain 2: AnyWork
  {
    id: 'edge-9',
    sourceNodeId: 'email-domains',
    targetNodeId: 'dom-anywork',
    relationshipType: 'owns',
    path: 'M 190 125 C 235 125, 235 385, 280 385',
    isDashed: true,
    isActive: false,
  },
  {
    id: 'edge-10',
    sourceNodeId: 'dom-anywork',
    targetNodeId: 'web-anywork-landing',
    relationshipType: 'resolves_to',
    path: 'M 450 385 C 505 385, 505 385, 560 385',
    isActive: false,
  },
  {
    id: 'edge-11',
    sourceNodeId: 'server-vps01',
    targetNodeId: 'web-anywork-landing',
    relationshipType: 'hosts',
    path: 'M 630 250 C 630 300, 600 320, 600 355',
    isDashed: true,
    isActive: false,
  },
  {
    id: 'edge-proj-3',
    sourceNodeId: 'web-anywork-landing',
    targetNodeId: 'proj-anywork',
    relationshipType: 'attached_to',
    path: 'M 730 385 C 775 385, 775 385, 820 385',
    isActive: false,
  },

  // Chain 3: DigitalOcean AI BOS
  {
    id: 'edge-12',
    sourceNodeId: 'email-servers',
    targetNodeId: 'prov-do',
    relationshipType: 'owns',
    path: 'M 190 495 C 235 495, 235 495, 280 495',
    isActive: false,
  },
  {
    id: 'edge-13',
    sourceNodeId: 'prov-do',
    targetNodeId: 'server-aibos',
    relationshipType: 'hosts',
    path: 'M 450 495 C 495 495, 495 495, 540 495',
    isActive: false,
  },
  {
    id: 'edge-14',
    sourceNodeId: 'server-aibos',
    targetNodeId: 'web-aibos-admin',
    relationshipType: 'hosts',
    path: 'M 710 495 C 765 495, 765 495, 820 495',
    isActive: false,
  },
  {
    id: 'edge-15',
    sourceNodeId: 'web-aibos-admin',
    targetNodeId: 'dom-admin-worknai',
    relationshipType: 'resolves_to',
    path: 'M 990 495 C 1040 495, 1040 495, 1090 495',
    isActive: false,
  },
  {
    id: 'edge-proj-4',
    sourceNodeId: 'dom-admin-worknai',
    targetNodeId: 'proj-aibos',
    relationshipType: 'attached_to',
    path: 'M 1260 495 C 1305 495, 1305 495, 1350 495',
    isActive: false,
  },

  // Chain 4: Legacy Personal
  {
    id: 'edge-16',
    sourceNodeId: 'email-aman',
    targetNodeId: 'prov-vultr',
    relationshipType: 'owns',
    path: 'M 190 625 C 235 625, 235 625, 280 625',
    isActive: false,
  },
  {
    id: 'edge-17',
    sourceNodeId: 'prov-vultr',
    targetNodeId: 'server-legacy',
    relationshipType: 'hosts',
    path: 'M 450 625 C 495 625, 495 625, 540 625',
    isActive: false,
  },
  {
    id: 'edge-18',
    sourceNodeId: 'server-legacy',
    targetNodeId: 'web-legacy-blog',
    relationshipType: 'hosts',
    path: 'M 710 625 C 765 625, 765 625, 820 625',
    isActive: false,
  },
  {
    id: 'edge-proj-5',
    sourceNodeId: 'web-legacy-blog',
    targetNodeId: 'proj-legacy',
    relationshipType: 'attached_to',
    path: 'M 990 625 C 1040 625, 1040 625, 1090 625',
    isActive: false,
  },
];

export const INITIAL_GRAPH_METRICS: GraphSummaryMetrics = {
  totalAssetsCount: 24,
  weeklyGrowthLabel: 'Stored Records',
  relationshipClustersCount: 4,
  bottleneckNodeName: 'Production VPS 01',
  bottleneckWebsitesCount: 5,
  orphanedAssetsCount: 0,
  orphanedPercentageLabel: '100% Mapped',
};

export const FILTER_COUNTS = {
  all: 24,
  email: 4,
  provider: 4,
  domain: 4,
  website: 5,
  server: 3,
  project: 4,
};
