import { AccountsSummary, EmailGroup, UnmappedAsset, ProviderAccount } from './accounts.types';

export const ACCOUNTS_SUMMARY: AccountsSummary = {
  managedEmailsCount: 4,
  managedEmailsSubtext: '4 Primary Groups',
  providerAccountsCount: 9,
  providerAccountsSubtext: 'Across 6 Core Vendors',
  domainsLinkedCount: 20,
  domainsLinkedSubtext: '20 Provider Records',
  serversLinkedCount: 7,
  serversLinkedSubtext: '4 Cloud Hosts',
  unmappedAssetsCount: 3,
  unmappedAssetsSubtext: 'Action Needed',
};

export const EMAIL_GROUPS_REFERENCE_DATA: EmailGroup[] = [
  {
    id: 'grp-domains',
    email: 'domains@worknai.com',
    icon: '@',
    iconIsMaterial: false,
    iconBgColor: 'bg-primary-fixed',
    iconTextColor: 'text-primary',
    subtitle: 'Primary company registrar contact for brand and strategic TLD assets',
    providerCount: 2,
    linkedAssetsCount: 20,
    badgeText: '2 Provider Accounts • 20 Mapped Relationships',
    providerAccounts: [
      {
        id: 'godaddy-main',
        providerCompany: 'GoDaddy',
        accountName: 'WorknAi GoDaddy Main',
        accountId: 'GD-89104',
        accountEmail: 'domains@worknai.com',
        logoLetter: 'GD',
        logoBgColor: 'bg-[#00A4A6]/10',
        logoTextColor: 'text-[#008385]',
        mappingStatus: 'mapped',
        mappingStatusLabel: 'User Mapped',
        domainsCount: 8,
        serversCount: 0,
        websitesCount: 6,
        sampleAssets: ['worknai.com', 'worknai.ai', 'anywork.in', 'getworkn.com'],
        moreAssetsCount: 4,
        autoRenewalText: 'Auto-renewal: Stored On (All 8)',
        project: 'WorknAi',
        notes: 'Primary corporate registrar account for core WorknAi properties.',
      },
      {
        id: 'namecheap-backup',
        providerCompany: 'Namecheap',
        accountName: 'Secondary Backup & Experimental',
        accountId: 'NC-44021',
        accountEmail: 'domains@worknai.com',
        logoLetter: 'NC',
        logoBgColor: 'bg-[#DE3723]/10',
        logoTextColor: 'text-[#DE3723]',
        mappingStatus: 'mapped',
        mappingStatusLabel: 'User Mapped',
        domainsCount: 4,
        serversCount: 0,
        websitesCount: 2,
        sampleAssets: ['workn.tech', 'worknai.org', 'worknlabs.io'],
        moreAssetsCount: 1,
        autoRenewalText: 'Auto-renewal: Stored On (3/4)',
        project: 'WorknAi Dev',
        notes: 'Secondary registrar for dev domains and exploratory brand extensions.',
      },
    ],
  },
  {
    id: 'grp-infra',
    email: 'infra@worknai.com',
    icon: 'terminal',
    iconIsMaterial: true,
    iconBgColor: 'bg-tertiary-fixed',
    iconTextColor: 'text-tertiary',
    subtitle: 'DevOps, cloud compute nodes, reverse proxies, and production infrastructure',
    providerCount: 3,
    linkedAssetsCount: 25,
    estimatedCostMonthly: 'Est. Spend: ₹5,051/mo',
    badgeText: '3 Provider Accounts • 25 Mapped Relationships • Est. Spend: ₹5,051/mo',
    providerAccounts: [
      {
        id: 'hostinger-main',
        providerCompany: 'Hostinger',
        accountName: 'WorknAi Main',
        accountId: 'HT-92813',
        accountEmail: 'infra@worknai.com',
        logoLetter: 'HO',
        logoBgColor: 'bg-[#673DE6]/10',
        logoTextColor: 'text-[#673DE6]',
        mappingStatus: 'mapped',
        mappingStatusLabel: 'User Mapped',
        domainsCount: 2,
        serversCount: 3,
        websitesCount: 9,
        sampleAssets: ['Production VPS 01', 'Staging Node B'],
        moreAssetsCount: 1,
        estimatedCostMonthly: 'Estimated Cost: ₹2,840/mo',
        project: 'WorknAi',
        notes: 'Core VPS host holding primary web and API applications.',
      },
      {
        id: 'digitalocean-team',
        providerCompany: 'DigitalOcean',
        accountName: 'Team DO',
        accountId: 'DO-TEAM-01',
        accountEmail: 'infra@worknai.com',
        logoLetter: 'DO',
        logoBgColor: 'bg-[#0080FF]/10',
        logoTextColor: 'text-[#0080FF]',
        mappingStatus: 'mapped',
        mappingStatusLabel: 'User Mapped',
        domainsCount: 0,
        serversCount: 2,
        websitesCount: 6,
        sampleAssets: ['AI BOS Droplet', 'Telemetry Analytics'],
        estimatedCostMonthly: 'Estimated Cost: ₹1,750/mo',
        project: 'AI BOS',
        notes: 'FastAPI compute clusters and high throughput ingestion sinks.',
      },
      {
        id: 'hetzner-storage',
        providerCompany: 'Hetzner Cloud',
        accountName: 'Storage & Archival',
        accountId: 'HZ-STORAGE-04',
        accountEmail: 'infra@worknai.com',
        logoLetter: 'HZ',
        logoBgColor: 'bg-[#D50C2D]/10',
        logoTextColor: 'text-[#D50C2D]',
        mappingStatus: 'mapped',
        mappingStatusLabel: 'User Mapped',
        domainsCount: 0,
        serversCount: 1,
        websitesCount: 2,
        sampleAssets: ['Backup Storage Box', 'Snapshot Vault'],
        estimatedCostMonthly: 'Estimated Cost: ₹461/mo',
        project: 'WorknAi',
        notes: 'Cold snapshot repository and disk backup box.',
      },
    ],
  },
  {
    id: 'grp-personal',
    email: 'aman@gmail.com',
    icon: 'badge',
    iconIsMaterial: true,
    iconBgColor: 'bg-secondary-container',
    iconTextColor: 'text-on-secondary-fixed',
    subtitle: 'Personal founder account holding early prototyping server and DNS zones',
    providerCount: 2,
    linkedAssetsCount: 12,
    badgeText: '2 Provider Accounts • 12 Mapped Relationships • Legacy Mapping',
    providerAccounts: [
      {
        id: 'vultr-legacy',
        providerCompany: 'Vultr',
        accountName: 'Legacy Personal Vultr',
        accountId: 'VU-LEGACY-09',
        accountEmail: 'aman@gmail.com',
        logoLetter: 'VU',
        logoBgColor: 'bg-[#007BFC]/10',
        logoTextColor: 'text-[#007BFC]',
        mappingStatus: 'stored',
        mappingStatusLabel: 'Stored Record',
        domainsCount: 0,
        serversCount: 1,
        websitesCount: 1,
        sampleAssets: ['legacy.worknai.com (VPS)'],
        estimatedCostMonthly: 'Estimated Cost: ₹950/mo',
        project: 'Legacy',
        notes: 'Early testbed VPS with legacy client showcase.',
      },
      {
        id: 'cloudflare-free',
        providerCompany: 'Cloudflare',
        accountName: 'Personal Free Tier',
        accountId: 'CF-FREE-01',
        accountEmail: 'aman@gmail.com',
        logoLetter: 'CF',
        logoBgColor: 'bg-[#F38020]/10',
        logoTextColor: 'text-[#F38020]',
        mappingStatus: 'mapped',
        mappingStatusLabel: 'User Mapped',
        domainsCount: 4,
        serversCount: 0,
        websitesCount: 4,
        workersCount: 2,
        sampleAssets: ['worknai.com (DNS)', 'worknai.ai (DNS)'],
        moreAssetsCount: 2,
        estimatedCostMonthly: 'Estimated Cost: Free Tier (₹0/mo)',
        project: 'WorknAi',
        notes: 'DNS proxy delegation and edge SSL certificate routing.',
      },
    ],
  },
  {
    id: 'grp-billing',
    email: 'billing@worknai.com',
    icon: 'receipt_long',
    iconIsMaterial: true,
    iconBgColor: 'bg-surface-container-high',
    iconTextColor: 'text-on-surface',
    subtitle: 'Automated tax invoices, GSTIN reconciliations, and cloud identity accounts',
    providerCount: 2,
    linkedAssetsCount: 2,
    badgeText: '2 Provider Accounts • 2 Mapped Relationships • Invoicing & Identity',
    providerAccounts: [
      {
        id: 'aws-fin',
        providerCompany: 'Amazon Web Services',
        accountName: 'worknai-corp-fin',
        accountId: 'AWS-4910-3819',
        accountEmail: 'billing@worknai.com',
        logoLetter: 'AWS',
        logoBgColor: 'bg-[#FF9900]/10',
        logoTextColor: 'text-[#D47D00]',
        mappingStatus: 'stored',
        mappingStatusLabel: 'Stored Record',
        domainsCount: 2,
        serversCount: 0,
        websitesCount: 0,
        sampleAssets: ['Route53 DNS Zone (worknai.internal)'],
        estimatedCostMonthly: 'Billing Model: Pay-as-you-go',
        project: 'WorknAi',
        notes: 'Consolidated corporate billing and Route53 private hosted zones.',
      },
      {
        id: 'gcp-org',
        providerCompany: 'Google Cloud Platform',
        accountName: 'worknai-billing-org',
        accountId: 'GCP-BILL-02',
        accountEmail: 'billing@worknai.com',
        logoLetter: 'GCP',
        logoBgColor: 'bg-[#4285F4]/10',
        logoTextColor: 'text-[#4285F4]',
        mappingStatus: 'stored',
        mappingStatusLabel: 'Stored Record',
        domainsCount: 0,
        serversCount: 0,
        websitesCount: 0,
        sampleAssets: ['Google Workspace & Cloud Identity'],
        estimatedCostMonthly: 'Billing Model: Consolidated Billing',
        project: 'WorknAi',
        notes: 'Google Cloud identity organization and domain verification hub.',
      },
    ],
  },
];

export const UNMAPPED_ASSETS_REFERENCE_DATA: UnmappedAsset[] = [
  {
    id: 'unmapped-1',
    name: 'clientportal.com',
    assetType: 'Domain',
    currentProvider: 'GoDaddy',
    missingRelationship: 'Account Email unassigned',
    actionLabel: 'Map Account',
  },
  {
    id: 'unmapped-2',
    name: 'Legacy VPS',
    subtext: '(legacy.worknai.com)',
    assetType: 'Server',
    currentProvider: 'Vultr',
    missingRelationship: 'Project & Dedicated Email unassigned',
    actionLabel: 'Complete Mapping',
  },
  {
    id: 'unmapped-3',
    name: 'worknlabs.io DNS',
    assetType: 'Website / Zone',
    currentProvider: 'Cloudflare',
    missingRelationship: 'Target Server unmapped',
    actionLabel: 'Link Server',
  },
];

export function getAllProviderAccounts(): ProviderAccount[] {
  return EMAIL_GROUPS_REFERENCE_DATA.flatMap((grp) => grp.providerAccounts);
}
