import { WebsitesReferenceDataset } from './websites.types';

export const WEBSITES_REFERENCE_DATA: WebsitesReferenceDataset = {
  summary: {
    totalAssets: 18,
    productionCount: 12,
    stagingDevCount: 4,
    attentionCount: 2,
    serversUsedCount: 6,
    connectedDomainsCount: 24,
  },

  websites: [
    {
      id: 'web-1',
      name: 'WorknAi Website',
      avatarLetter: 'W',
      avatarBgColor: 'bg-primary-fixed',
      avatarTextColor: 'text-primary',
      domain: 'worknai.com',
      routeNote: '+ www.worknai.com',
      environment: 'Production',
      serverName: 'Production VPS 01',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'prod-01',
      project: 'WorknAi',
      techStack: 'Next.js 14',
      port: 3000,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 68d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 2,
      ipAddress: '103.21.58.112',
      notes: 'Primary SSR web application for WorknAi company profile.',
    },
    {
      id: 'web-2',
      name: 'WorknAi API',
      avatarLetter: 'W',
      avatarBgColor: 'bg-primary-fixed',
      avatarTextColor: 'text-primary',
      domain: 'api.worknai.com',
      routeNote: '/v1/healthcheck',
      environment: 'Production',
      serverName: 'Production VPS 01',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'prod-01',
      project: 'WorknAi',
      techStack: 'Node.js',
      port: 8080,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: "Recorded • Let's Encrypt",
      sslDetails: "Let's Encrypt wildcard • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '103.21.58.112',
      notes: 'Core REST and GraphQL gateway for WorknAi services.',
    },
    {
      id: 'web-3',
      name: 'AI BOS Admin',
      avatarLetter: 'B',
      avatarBgColor: 'bg-secondary-fixed',
      avatarTextColor: 'text-on-secondary-fixed',
      domain: 'admin.worknai.com',
      routeNote: 'Routed via Caddy',
      environment: 'Production',
      serverName: 'AI BOS Server',
      serverProvider: 'DigitalOcean',
      serverAccountEmail: 'servers@worknai.com',
      serverId: 'aibos',
      project: 'AI BOS',
      techStack: 'React',
      port: 4000,
      reverseProxy: 'Caddy',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 68d',
      sslDetails: 'Cloudflare Edge SSL • Stored Certificate Record',
      connectedDomainsCount: 1,
      ipAddress: '159.89.162.40',
      notes: 'Admin internal backoffice workspace dashboard.',
    },
    {
      id: 'web-4',
      name: 'AnyWork Landing',
      avatarLetter: 'A',
      avatarBgColor: 'bg-tertiary-fixed',
      avatarTextColor: 'text-tertiary',
      domain: 'anywork.in',
      routeNote: 'Nginx Reverse Proxy',
      environment: 'Production',
      serverName: 'Production VPS 01',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'prod-01',
      project: 'AnyWork',
      techStack: 'Next.js',
      port: 3001,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: "Recorded • Let's Encrypt",
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 2,
      ipAddress: '103.21.58.112',
      notes: 'Customer landing and signup page for AnyWork India.',
    },
    {
      id: 'web-5',
      name: 'AnyWork API Gateway',
      avatarLetter: 'A',
      avatarBgColor: 'bg-tertiary-fixed',
      avatarTextColor: 'text-tertiary',
      domain: 'api.anywork.in',
      routeNote: 'Edge Gateway',
      environment: 'Production',
      serverName: 'Production VPS 01',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'prod-01',
      project: 'AnyWork',
      techStack: 'Node.js',
      port: 8081,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 68d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '103.21.58.112',
      notes: 'AnyWork transaction and orchestration backend.',
    },
    {
      id: 'web-6',
      name: 'AI BOS Engine API',
      avatarLetter: 'B',
      avatarBgColor: 'bg-secondary-fixed',
      avatarTextColor: 'text-on-secondary-fixed',
      domain: 'engine.worknai.com',
      routeNote: 'Async Worker Pool',
      environment: 'Production',
      serverName: 'AI BOS Server',
      serverProvider: 'DigitalOcean',
      serverAccountEmail: 'servers@worknai.com',
      serverId: 'aibos',
      project: 'AI BOS',
      techStack: 'Python FastAPI',
      port: 8000,
      reverseProxy: 'Caddy',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 68d',
      sslDetails: 'Cloudflare Origin CA • Stored Certificate Record',
      connectedDomainsCount: 1,
      ipAddress: '159.89.162.40',
      notes: 'High throughput AI orchestration and inference router.',
    },
    {
      id: 'web-7',
      name: 'Dev Sandbox Portal',
      avatarLetter: 'S',
      avatarBgColor: 'bg-secondary-container',
      avatarTextColor: 'text-on-secondary-container',
      domain: 'sandbox.worknai.dev',
      routeNote: 'Feature Branch Previews',
      environment: 'Development',
      serverName: 'AnyWork Staging Node',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'staging',
      project: 'WorknAi Dev',
      techStack: 'Vite React',
      port: 5173,
      reverseProxy: 'Nginx',
      sslStatus: 'warning',
      sslLabel: 'Recorded • Self-Signed',
      sslDetails: 'Local Dev Certificate • Stored Record (Needs Attention)',
      connectedDomainsCount: 1,
      ipAddress: '103.21.59.84',
      notes: 'PR review and isolated experiment playground.',
    },
    {
      id: 'web-8',
      name: 'Legacy Client Blog',
      avatarLetter: 'L',
      avatarBgColor: 'bg-surface-container-high',
      avatarTextColor: 'text-secondary',
      domain: 'legacy.worknai.com',
      routeNote: 'Static archive cache',
      environment: 'Production',
      serverName: 'Legacy VPS',
      serverProvider: 'Vultr',
      serverAccountEmail: 'aman@gmail.com',
      serverId: 'legacy',
      project: 'Legacy',
      techStack: 'WordPress / PHP',
      port: 443,
      reverseProxy: 'Apache',
      sslStatus: 'expiring',
      sslLabel: 'Recorded • Expiring • 12d',
      sslDetails: "Certbot Let's Encrypt • Stored Record (Expiring in 12 days)",
      connectedDomainsCount: 1,
      ipAddress: '45.76.180.25',
      notes: 'Read-only archived blog and case study vault.',
    },
    {
      id: 'web-9',
      name: 'AnyWork Staging Web',
      avatarLetter: 'A',
      avatarBgColor: 'bg-tertiary-container',
      avatarTextColor: 'text-on-tertiary-container',
      domain: 'stg.anywork.ai',
      routeNote: 'Staging Web Mirror',
      environment: 'Staging',
      serverName: 'AnyWork Staging Node',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'staging',
      project: 'AnyWork',
      techStack: 'Next.js',
      port: 3000,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 45d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '103.21.59.84',
      notes: 'Pre-release staging candidate for AnyWork frontend.',
    },
    {
      id: 'web-10',
      name: 'AnyWork Staging API',
      avatarLetter: 'A',
      avatarBgColor: 'bg-tertiary-container',
      avatarTextColor: 'text-on-tertiary-container',
      domain: 'stg-api.anywork.ai',
      routeNote: 'Staging Backend',
      environment: 'Staging',
      serverName: 'AnyWork Staging Node',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'staging',
      project: 'AnyWork',
      techStack: 'Node.js',
      port: 8080,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 45d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '103.21.59.84',
      notes: 'Staging API gateway and database migration testbed.',
    },
    {
      id: 'web-11',
      name: 'AI BOS Web Portal',
      avatarLetter: 'B',
      avatarBgColor: 'bg-secondary-fixed',
      avatarTextColor: 'text-on-secondary-fixed',
      domain: 'app.aibos.cloud',
      routeNote: 'Customer App Interface',
      environment: 'Production',
      serverName: 'AI BOS Server',
      serverProvider: 'DigitalOcean',
      serverAccountEmail: 'servers@worknai.com',
      serverId: 'aibos',
      project: 'AI BOS',
      techStack: 'Next.js 14',
      port: 3000,
      reverseProxy: 'Caddy',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 68d',
      sslDetails: 'Cloudflare Edge • Stored Certificate Record',
      connectedDomainsCount: 1,
      ipAddress: '159.89.162.40',
      notes: 'AI BOS authenticated SaaS user console.',
    },
    {
      id: 'web-12',
      name: 'Dev Documentation Hub',
      avatarLetter: 'D',
      avatarBgColor: 'bg-surface-container-high',
      avatarTextColor: 'text-on-surface',
      domain: 'docs-dev.worknai.com',
      routeNote: 'Docusaurus Builder',
      environment: 'Development',
      serverName: 'AnyWork Staging Node',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'staging',
      project: 'WorknAi Dev',
      techStack: 'React / Vite',
      port: 3002,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 90d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '103.21.59.84',
      notes: 'Developer documentation and OpenAPI schema renderer.',
    },
    {
      id: 'web-13',
      name: 'Telemetry Proxy Node',
      avatarLetter: 'P',
      avatarBgColor: 'bg-primary-container',
      avatarTextColor: 'text-on-primary',
      domain: 'pulsecdn.net',
      routeNote: 'Edge CDN Proxy',
      environment: 'Production',
      serverName: 'Analytics Worker',
      serverProvider: 'DigitalOcean',
      serverAccountEmail: 'servers@worknai.com',
      serverId: 'analytics',
      project: 'WorknAi',
      techStack: 'Node.js',
      port: 8080,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 120d',
      sslDetails: 'Cloudflare Edge • Stored Certificate Record',
      connectedDomainsCount: 2,
      ipAddress: '139.59.34.19',
      notes: 'High speed static asset and telemetry ingestion proxy.',
    },
    {
      id: 'web-14',
      name: 'Internal Grafana Stack',
      avatarLetter: 'M',
      avatarBgColor: 'bg-secondary-fixed',
      avatarTextColor: 'text-on-secondary-fixed',
      domain: 'metrics.worknai.com',
      routeNote: 'Secured Monitoring Node',
      environment: 'Production',
      serverName: 'Analytics Worker',
      serverProvider: 'DigitalOcean',
      serverAccountEmail: 'servers@worknai.com',
      serverId: 'analytics',
      project: 'WorknAi',
      techStack: 'React / Vite',
      port: 3000,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 68d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '139.59.34.19',
      notes: 'Internal metrics visualizer and system health hub.',
    },
    {
      id: 'web-15',
      name: 'Log Engine Collector',
      avatarLetter: 'L',
      avatarBgColor: 'bg-surface-container-high',
      avatarTextColor: 'text-on-surface',
      domain: 'logs.worknai.internal',
      routeNote: 'Vector / Clickhouse',
      environment: 'Production',
      serverName: 'Analytics Worker',
      serverProvider: 'DigitalOcean',
      serverAccountEmail: 'servers@worknai.com',
      serverId: 'analytics',
      project: 'WorknAi',
      techStack: 'Python FastAPI',
      port: 8080,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Internal CA',
      sslDetails: 'WorknAi Internal Root CA • Stored Certificate Record',
      connectedDomainsCount: 1,
      ipAddress: '139.59.34.19',
      notes: 'Centralized log pipeline and telemetry sink.',
    },
    {
      id: 'web-16',
      name: 'Archival Vault Portal',
      avatarLetter: 'A',
      avatarBgColor: 'bg-surface-container-high',
      avatarTextColor: 'text-on-surface',
      domain: 'archive.worknai.com',
      routeNote: 'Cold Object Storage',
      environment: 'Production',
      serverName: 'Backup Storage Box',
      serverProvider: 'Hetzner',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'hetzner',
      project: 'WorknAi',
      techStack: 'Node.js',
      port: 8080,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 140d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '168.119.82.10',
      notes: 'Long term audit log repository and database snapshot indexer.',
    },
    {
      id: 'web-17',
      name: 'AnyWork Preview Node',
      avatarLetter: 'P',
      avatarBgColor: 'bg-secondary-container',
      avatarTextColor: 'text-on-secondary-container',
      domain: 'preview.worknai.com',
      routeNote: 'Ephemeral Deployment',
      environment: 'Development',
      serverName: 'AnyWork Staging Node',
      serverProvider: 'Hostinger',
      serverAccountEmail: 'infra@worknai.com',
      serverId: 'staging',
      project: 'AnyWork',
      techStack: 'Next.js',
      port: 3005,
      reverseProxy: 'Nginx',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 45d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '103.21.59.84',
      notes: 'Staging preview build for pull requests.',
    },
    {
      id: 'web-18',
      name: 'Aman Showcase Agency',
      avatarLetter: 'S',
      avatarBgColor: 'bg-surface-container-high',
      avatarTextColor: 'text-secondary',
      domain: 'devstudio.agency',
      routeNote: 'Portfolio Static Site',
      environment: 'Production',
      serverName: 'Legacy VPS',
      serverProvider: 'Vultr',
      serverAccountEmail: 'aman@gmail.com',
      serverId: 'legacy',
      project: 'Legacy',
      techStack: 'WordPress / PHP',
      port: 443,
      reverseProxy: 'Apache',
      sslStatus: 'healthy',
      sslLabel: 'Recorded • Valid • 110d',
      sslDetails: "Let's Encrypt • Stored Certificate Record",
      connectedDomainsCount: 1,
      ipAddress: '45.76.180.25',
      notes: 'Personal agency showcase site and case study index.',
    },
  ],

  filterOptions: {
    environments: [
      { label: 'Environment: All', value: 'all' },
      { label: 'Production', value: 'production' },
      { label: 'Staging', value: 'staging' },
      { label: 'Development', value: 'development' },
    ],
    servers: [
      { label: 'Server: All (6)', value: 'all' },
      { label: 'Production VPS 01 (Hostinger)', value: 'hostinger' },
      { label: 'AI BOS Server (DigitalOcean)', value: 'digitalocean' },
      { label: 'AnyWork Staging Node', value: 'staging-node' },
      { label: 'Legacy VPS (Vultr)', value: 'vultr' },
      { label: 'Analytics Worker', value: 'analytics' },
      { label: 'Backup Storage Box (Hetzner)', value: 'hetzner' },
    ],
    techStacks: [
      { label: 'Tech Stack: All', value: 'all' },
      { label: 'Next.js', value: 'next' },
      { label: 'Node.js', value: 'node' },
      { label: 'React / Vite', value: 'react' },
      { label: 'Python FastAPI', value: 'python' },
      { label: 'WordPress / PHP', value: 'wordpress' },
    ],
    sslStatuses: [
      { label: 'SSL Status: All', value: 'all' },
      { label: 'Valid Recorded', value: 'healthy' },
      { label: 'Expiring Soon', value: 'expiring' },
      { label: 'Self-Signed / Warning', value: 'warning' },
    ],
    projects: [
      { label: 'Project: All', value: 'all' },
      { label: 'WorknAi', value: 'worknai' },
      { label: 'AI BOS', value: 'aibos' },
      { label: 'AnyWork', value: 'anywork' },
      { label: 'Legacy', value: 'legacy' },
      { label: 'WorknAi Dev', value: 'worknai-dev' },
    ],
  },
};
