import {
  AlertItem,
  AlertSummaryMetrics,
  HealthMatrixItem,
  MonitoringCoverageItem,
  AlertRuleItem,
  RenewalHorizonItem,
} from './alerts.types';

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'alert-1',
    severity: 'CRITICAL',
    entityType: 'domain',
    type: 'Domain Expiry',
    domain: 'worknai.com',
    title: 'Critical Domain Expiry Alert',
    riskInsight: 'Domain expires in 4 days and auto-renew is disabled in portfolio record.',
    advisory: 'This domain expires in 4 days and auto-renew is currently marked as disabled in the portfolio record.',
    triggeredDate: '04 Sep 2026',
    dueDate: '08 Sep 2026',
    daysRemaining: 4,
    daysRemainingLabel: '4 Days Left',
    status: 'unread',
    registrarOrProvider: 'GoDaddy LLC',
    renewalPriceFormatted: '₹1,299 / yr',
    autoRenewStatus: 'Off (Risk Detected)',
    autoRenewIsRisk: true,
    nameservers: 'ns1.godaddy.com, ns2.godaddy.com',
    sslStatus: 'Active (64d left)',
    targetRoute: '/domains/domain-1',
    isCriticalActionCard: true,
    isUrgent: true,
    dataSourceNote: 'Calculated from stored expiry metadata',
  },
  {
    id: 'alert-2',
    severity: 'CRITICAL',
    entityType: 'domain',
    type: 'Auto-Renew',
    domain: 'businesshub.in',
    title: 'Auto-Renew Disabled / Expiry Warning',
    riskInsight: 'Auto-renew disabled; renewal review required in stored portfolio.',
    advisory: 'Auto-renew is disabled and domain expiration window is under 7 days in the reference dataset.',
    triggeredDate: '04 Sep 2026',
    dueDate: '10 Sep 2026',
    daysRemaining: 6,
    daysRemainingLabel: '6 Days Left',
    status: 'unread',
    registrarOrProvider: 'Hostinger',
    renewalPriceFormatted: '₹899 / yr',
    autoRenewStatus: 'Off (Manual Required)',
    autoRenewIsRisk: true,
    nameservers: 'ns1.dns-parking.com, ns2.dns-parking.com',
    sslStatus: 'Active (112d left)',
    targetRoute: '/domains/domain-3',
    isCriticalActionCard: true,
    isUrgent: true,
    dataSourceNote: 'Calculated from stored expiry metadata',
  },
  {
    id: 'alert-3',
    severity: 'WARNING',
    entityType: 'domain',
    type: 'Domain Expiry',
    domain: 'anywork.ai',
    title: 'Upcoming Domain Expiration',
    riskInsight: 'Domain expires in 12 days. Standard renewal rate ₹6,850/yr.',
    advisory: 'Standard renewal rate ₹6,850/yr applies. Portfolio budget and auto-renew confirmation recommended.',
    triggeredDate: '01 Sep 2026',
    dueDate: '16 Sep 2026',
    daysRemaining: 12,
    daysRemainingLabel: '12 Days Left',
    status: 'unread',
    registrarOrProvider: 'Namecheap',
    renewalPriceFormatted: '₹6,850 / yr',
    autoRenewStatus: 'On (Stored Preference)',
    nameservers: 'dns1.registrar-servers.com, dns2.registrar-servers.com',
    sslStatus: 'Active (240d left)',
    targetRoute: '/domains/domain-4',
    dataSourceNote: 'Calculated from stored expiry metadata',
  },
  {
    id: 'alert-4',
    severity: 'WARNING',
    entityType: 'ssl',
    type: 'SSL Certificate',
    domain: 'clientportal.com',
    title: 'SSL Certificate Pending Renewal',
    riskInsight: "Let's Encrypt SSL expires in 12 days; stored certificate record requires rotation.",
    advisory: 'Stored certificate record indicates expiration in 12 days. Automated renewal challenge pending verification.',
    triggeredDate: '02 Sep 2026',
    dueDate: '16 Sep 2026',
    daysRemaining: 12,
    daysRemainingLabel: '12 Days Left',
    status: 'unread',
    registrarOrProvider: 'GoDaddy LLC',
    renewalPriceFormatted: '₹1,499 / yr',
    autoRenewStatus: 'On (Enabled)',
    nameservers: 'ns01.domaincontrol.com, ns02.domaincontrol.com',
    sslStatus: 'Expiring Soon (12d left)',
    targetRoute: '/websites/web-2',
    dataSourceNote: 'Stored SSL certificate record',
  },
  {
    id: 'alert-5',
    severity: 'WARNING',
    entityType: 'domain',
    type: 'Domain Expiry',
    domain: 'aibos.ai',
    title: '30-Day Expiry Notice',
    riskInsight: 'Domain enters 30-day renewal cycle on 03 Oct 2026.',
    advisory: 'Domain enters 30-day renewal cycle on 03 Oct 2026. Stored auto-renew preference is On.',
    triggeredDate: '03 Sep 2026',
    dueDate: '03 Oct 2026',
    daysRemaining: 29,
    daysRemainingLabel: '29 Days Left',
    status: 'unread',
    registrarOrProvider: 'AWS Route 53',
    renewalPriceFormatted: '₹7,200 / yr',
    autoRenewStatus: 'On (Stored Preference)',
    nameservers: 'ns-1120.awsdns-12.org, ns-1678.awsdns-17.co.uk',
    sslStatus: 'Active (180d left)',
    targetRoute: '/domains/domain-5',
    dataSourceNote: 'Calculated from stored expiry metadata',
  },
  {
    id: 'alert-6',
    severity: 'WARNING',
    entityType: 'dns',
    type: 'DNSSEC Alert',
    domain: 'pulsecdn.net',
    title: 'DNSSEC Key Expiration Notice',
    riskInsight: 'DNSSEC record signature expiring in 14 days on Cloudflare.',
    advisory: 'DS record signature rollover needed on Cloudflare DNS within 14 days to preserve validation.',
    triggeredDate: '01 Sep 2026',
    dueDate: '18 Sep 2026',
    daysRemaining: 14,
    daysRemainingLabel: '14 Days Left',
    status: 'unread',
    registrarOrProvider: 'Cloudflare Registrar',
    renewalPriceFormatted: '₹950 / yr',
    autoRenewStatus: 'On (Enabled)',
    nameservers: 'art.ns.cloudflare.com, bella.ns.cloudflare.com',
    sslStatus: 'Active (Cloudflare Edge)',
    targetRoute: '/domains/domain-6',
    dataSourceNote: 'Stored DNS configuration record',
  },
  {
    id: 'alert-7',
    severity: 'WARNING',
    entityType: 'server',
    type: 'Server Renewal',
    domain: 'vps-prod-blr-1',
    title: 'VPS Server Renewal Approaching',
    riskInsight: 'Hostinger VPS monthly billing cycle ends in 14 days (18 Sep 2026).',
    advisory: 'Hostinger 4 vCPU KVM VPS renewal is due on 18 Sep 2026. Verify payment card on file.',
    triggeredDate: '04 Sep 2026',
    dueDate: '18 Sep 2026',
    daysRemaining: 14,
    daysRemainingLabel: '14 Days Left',
    status: 'unread',
    registrarOrProvider: 'Hostinger VPS',
    renewalPriceFormatted: '₹1,299 / mo',
    autoRenewStatus: 'On (Auto-Debit)',
    ipAddress: '103.121.89.42',
    targetRoute: '/servers/srv-1',
    dataSourceNote: 'Stored server inventory record',
  },
  {
    id: 'alert-8',
    severity: 'WARNING',
    entityType: 'account',
    type: 'Unmapped Asset',
    domain: 'api-gateway-node-2',
    title: 'Unmapped Infrastructure Asset',
    riskInsight: 'Server record has no mapped provider account or login email association.',
    advisory: 'This VPS asset is registered in inventory but not associated with any verified provider account.',
    triggeredDate: '02 Sep 2026',
    dueDate: '15 Sep 2026',
    daysRemaining: 11,
    daysRemainingLabel: 'Attention Needed',
    status: 'unread',
    registrarOrProvider: 'Unmapped Provider',
    autoRenewStatus: 'Unmapped',
    ipAddress: '159.89.162.99',
    targetRoute: '/accounts',
    dataSourceNote: 'Account mapping inconsistency',
  },
  {
    id: 'alert-9',
    severity: 'UPCOMING',
    entityType: 'domain',
    type: 'Upcoming Renewal',
    domain: 'goairclass.com',
    title: 'Upcoming Renewal Notice',
    riskInsight: 'Stored auto-renew preference is On. Review the upcoming renewal date.',
    advisory: 'Upcoming renewal recorded for 18 Jan 2027 in stored portfolio records.',
    triggeredDate: '28 Aug 2026',
    dueDate: '18 Jan 2027',
    daysRemaining: 136,
    daysRemainingLabel: '136 Days Left',
    status: 'read',
    registrarOrProvider: 'Namecheap',
    renewalPriceFormatted: '₹1,150 / yr',
    autoRenewStatus: 'On (Stored Preference)',
    nameservers: 'dns1.registrar-servers.com, dns2.registrar-servers.com',
    sslStatus: 'Active (82d left)',
    targetRoute: '/domains/domain-2',
    dataSourceNote: 'Calculated from stored expiry metadata',
  },
  {
    id: 'alert-10',
    severity: 'UPCOMING',
    entityType: 'domain',
    type: 'Upcoming Renewal',
    domain: 'finpilot.io',
    title: 'Upcoming Renewal Notice',
    riskInsight: 'Upcoming renewal recorded for 08 Mar 2027.',
    advisory: 'Stored renewal date is 08 Mar 2027. Stored auto-renew preference is enabled on Porkbun LLC.',
    triggeredDate: '25 Aug 2026',
    dueDate: '08 Mar 2027',
    daysRemaining: 184,
    daysRemainingLabel: '184 Days Left',
    status: 'read',
    registrarOrProvider: 'Porkbun LLC',
    renewalPriceFormatted: '₹2,499 / yr',
    autoRenewStatus: 'On (Stored Preference)',
    nameservers: 'curitiba.ns.porkbun.com, salvador.ns.porkbun.com',
    sslStatus: 'Active (190d left)',
    targetRoute: '/domains',
    dataSourceNote: 'Calculated from stored expiry metadata',
  },
  {
    id: 'alert-11',
    severity: 'RESOLVED',
    entityType: 'domain',
    type: 'Domain Expiry',
    domain: 'cloudscale.dev',
    title: 'Stored Domain Expiry Record Updated',
    riskInsight: 'Stored domain record now shows a later expiration date.',
    advisory: 'Stored domain reference record now shows a later expiration date through August 2027.',
    triggeredDate: '20 Aug 2026',
    dueDate: '28 Aug 2027',
    daysRemaining: 357,
    daysRemainingLabel: 'Renewed',
    status: 'resolved',
    registrarOrProvider: 'Cloudflare Registrar',
    renewalPriceFormatted: '₹899 / yr',
    autoRenewStatus: 'On (Active)',
    targetRoute: '/domains',
    dataSourceNote: 'Stored Resolution Record',
  },
  {
    id: 'alert-12',
    severity: 'RESOLVED',
    entityType: 'ssl',
    type: 'SSL Certificate',
    domain: 'worknflow.co.in',
    title: 'Stored SSL Reference Record Updated',
    riskInsight: 'Stored SSL reference record now shows a later certificate expiry.',
    advisory: 'Stored SSL reference record now shows a later certificate expiry date through November 2026.',
    triggeredDate: '18 Aug 2026',
    dueDate: '24 Nov 2026',
    daysRemaining: 80,
    daysRemainingLabel: 'Resolved',
    status: 'resolved',
    registrarOrProvider: 'Hostinger',
    autoRenewStatus: 'On (Automated)',
    targetRoute: '/websites',
    dataSourceNote: 'Stored Resolution Record',
  },
];

export const INITIAL_HEALTH_MATRIX: HealthMatrixItem[] = [
  {
    id: 'hm-1',
    domain: 'worknai.com',
    sslHealth: "Let's Encrypt (64d)",
    dnsStatus: 'Cloudflare Configured',
    autoRenewStatus: 'Off (Risk Detected)',
    autoRenewIsRisk: true,
    daysRemaining: 4,
    daysRemainingLabel: '4 days',
    overallHealth: 'Critical',
    overallHealthVariant: 'error',
    targetRoute: '/domains/domain-1',
  },
  {
    id: 'hm-2',
    domain: 'businesshub.in',
    sslHealth: 'ZeroSSL (112d)',
    dnsStatus: 'Hostinger DNS',
    autoRenewStatus: 'Off (Review Needed)',
    autoRenewIsRisk: true,
    daysRemaining: 6,
    daysRemainingLabel: '6 days',
    overallHealth: 'Critical',
    overallHealthVariant: 'error',
    targetRoute: '/domains/domain-3',
  },
  {
    id: 'hm-3',
    domain: 'anywork.ai',
    sslHealth: 'Sectigo (240d)',
    dnsStatus: 'Namecheap Basic',
    autoRenewStatus: 'On (Enabled)',
    daysRemaining: 12,
    daysRemainingLabel: '12 days',
    overallHealth: 'Warning',
    overallHealthVariant: 'warning',
    targetRoute: '/domains/domain-4',
  },
  {
    id: 'hm-4',
    domain: 'clientportal.com',
    sslHealth: "Let's Encrypt (12d)",
    dnsStatus: 'GoDaddy Standard',
    autoRenewStatus: 'On (Enabled)',
    daysRemaining: 12,
    daysRemainingLabel: '12 days',
    overallHealth: 'Warning',
    overallHealthVariant: 'warning',
    targetRoute: '/websites/web-2',
  },
  {
    id: 'hm-5',
    domain: 'aibos.ai',
    sslHealth: 'Google Trust (180d)',
    dnsStatus: 'AWS Route 53',
    autoRenewStatus: 'On (Enabled)',
    daysRemaining: 29,
    daysRemainingLabel: '29 days',
    overallHealth: 'Warning',
    overallHealthVariant: 'warning',
    targetRoute: '/domains/domain-5',
  },
  {
    id: 'hm-6',
    domain: 'pulsecdn.net',
    sslHealth: 'Cloudflare Edge',
    dnsStatus: 'DNSSEC (14d left)',
    autoRenewStatus: 'On (Enabled)',
    daysRemaining: 204,
    daysRemainingLabel: '204 days',
    overallHealth: 'Warning',
    overallHealthVariant: 'warning',
    targetRoute: '/domains/domain-6',
  },
  {
    id: 'hm-7',
    domain: 'goairclass.com',
    sslHealth: 'ZeroSSL (82d)',
    dnsStatus: 'Namecheap Basic',
    autoRenewStatus: 'On (Enabled)',
    daysRemaining: 136,
    daysRemainingLabel: '136 days',
    overallHealth: 'Healthy',
    overallHealthVariant: 'primary',
    targetRoute: '/domains/domain-2',
  },
  {
    id: 'hm-8',
    domain: 'finpilot.io',
    sslHealth: "Let's Encrypt (190d)",
    dnsStatus: 'Porkbun DNS',
    autoRenewStatus: 'On (Enabled)',
    daysRemaining: 184,
    daysRemainingLabel: '184 days',
    overallHealth: 'Healthy',
    overallHealthVariant: 'primary',
    targetRoute: '/domains',
  },
];

export const INITIAL_MONITORING_COVERAGE: MonitoringCoverageItem[] = [
  {
    id: 'mc-1',
    assetType: 'Domain Portfolios',
    icon: 'dns',
    inventoryCount: 42,
    inventoryStatus: 'Stored Records Available',
    monitoringStatus: 'Calculated From Dates',
    monitoringStatusLabel: 'Expiry Calculated (Stored Metadata)',
    details: 'Expirations and auto-renew states evaluated from stored portfolio records.',
    badgeVariant: 'primary',
  },
  {
    id: 'mc-2',
    assetType: 'SSL Certificates',
    icon: 'shield',
    inventoryCount: 28,
    inventoryStatus: 'Reference Records Stored',
    monitoringStatus: 'Reference Snapshot',
    monitoringStatusLabel: 'Snapshot Evaluated (No Background Probes)',
    details: 'Validity periods calculated from stored certificate issuance dates.',
    badgeVariant: 'warning',
  },
  {
    id: 'mc-3',
    assetType: 'Servers & VPS',
    icon: 'memory',
    inventoryCount: 8,
    inventoryStatus: 'Inventory Stored',
    monitoringStatus: 'Not Connected',
    monitoringStatusLabel: 'Live CPU/RAM/Uptime Probes Not Connected',
    details: 'Server records store OS and IP mapping; runtime telemetry requires future agent integration.',
    badgeVariant: 'neutral',
  },
  {
    id: 'mc-4',
    assetType: 'Websites & Applications',
    icon: 'web',
    inventoryCount: 14,
    inventoryStatus: 'Mappings Stored',
    monitoringStatus: 'Not Connected',
    monitoringStatusLabel: 'HTTP Live Heartbeat Not Connected',
    details: 'Web records maintain target server mappings; automated uptime probes are not connected.',
    badgeVariant: 'neutral',
  },
  {
    id: 'mc-5',
    assetType: 'DNS & Nameservers',
    icon: 'hub',
    inventoryCount: 42,
    inventoryStatus: 'DNS Snapshot Stored',
    monitoringStatus: 'Reference Snapshot',
    monitoringStatusLabel: 'DNSSEC Reference Snapshot',
    details: 'Authoritative nameserver and DNSSEC status evaluated from stored zone records.',
    badgeVariant: 'warning',
  },
  {
    id: 'mc-6',
    assetType: 'Notification Channels',
    icon: 'notifications_active',
    inventoryCount: 4,
    inventoryStatus: 'Configuration Only',
    monitoringStatus: 'Configuration Only',
    monitoringStatusLabel: 'Email / WhatsApp Delivery Not Connected',
    details: 'Alert preferences are stored locally in UI state; no external messages are dispatched.',
    badgeVariant: 'neutral',
  },
];

export const INITIAL_ALERT_RULES: AlertRuleItem[] = [
  {
    id: 'rule-1',
    name: 'Critical Domain Expiration (≤ 7 Days)',
    description: 'Trigger high-priority alert when a domain enters 7-day critical renewal window.',
    category: 'Domain Lifecycle',
    severity: 'CRITICAL',
    thresholdDays: 7,
    thresholdOptions: [3, 7, 10],
    enabled: true,
    deliveryChannelHint: 'In-App Dashboard (Local State)',
  },
  {
    id: 'rule-2',
    name: 'Advance Domain Expiry Notice (≤ 30 Days)',
    description: 'Advance notice when a registered domain enters standard 30-day renewal cycle.',
    category: 'Domain Lifecycle',
    severity: 'WARNING',
    thresholdDays: 30,
    thresholdOptions: [15, 30, 45, 60],
    enabled: true,
    deliveryChannelHint: 'In-App Dashboard (Local State)',
  },
  {
    id: 'rule-3',
    name: 'SSL Certificate Expiration (≤ 14 Days)',
    description: "Alert when Let's Encrypt or custom SSL certificate is nearing expiration.",
    category: 'Security & SSL',
    severity: 'WARNING',
    thresholdDays: 14,
    thresholdOptions: [7, 14, 30],
    enabled: true,
    deliveryChannelHint: 'In-App Dashboard (Local State)',
  },
  {
    id: 'rule-4',
    name: 'DNSSEC Key Rollover & DNS Attention',
    description: 'Notice for DNSSEC DS record signature expiration or authoritative NS drift.',
    category: 'DNS Infrastructure',
    severity: 'WARNING',
    thresholdDays: 14,
    thresholdOptions: [7, 14, 30],
    enabled: true,
    deliveryChannelHint: 'In-App Dashboard (Local State)',
  },
  {
    id: 'rule-5',
    name: 'Server & Cloud Billing Cycle (≤ 14 Days)',
    description: 'Reminder before monthly or annual VPS/server renewal invoice is generated.',
    category: 'Infrastructure Billing',
    severity: 'WARNING',
    thresholdDays: 14,
    thresholdOptions: [7, 14, 21],
    enabled: true,
    deliveryChannelHint: 'In-App Dashboard (Local State)',
  },
  {
    id: 'rule-6',
    name: 'Unmapped Infrastructure Asset Detection',
    description: 'Flag domains, servers, or websites without associated provider accounts.',
    category: 'Account & Ownership',
    severity: 'WARNING',
    thresholdDays: 0,
    thresholdOptions: [0],
    enabled: true,
    deliveryChannelHint: 'In-App Dashboard (Local State)',
  },
];

export const INITIAL_RENEWAL_HORIZON: RenewalHorizonItem[] = [

  {
    id: 'rh-7d',
    label: 'Next 7 Days',
    domainsCount: 2,
    estimatedCostFormatted: '₹2,198 est. renewal cost',
    severity: 'error',
    progressPercent: 15,
  },
  {
    id: 'rh-30d',
    label: 'Next 30 Days',
    domainsCount: 6,
    estimatedCostFormatted: '₹9,899 est. renewal cost',
    severity: 'warning',
    progressPercent: 45,
  },
  {
    id: 'rh-60d',
    label: 'Next 60 Days',
    domainsCount: 4,
    estimatedCostFormatted: '₹4,600 est. renewal cost',
    severity: 'neutral',
    progressPercent: 25,
  },
  {
    id: 'rh-90d',
    label: 'Next 90 Days',
    domainsCount: 7,
    estimatedCostFormatted: '₹8,350 est. renewal cost',
    severity: 'primary',
    progressPercent: 55,
  },
];

export const RENEWAL_HORIZONS = INITIAL_RENEWAL_HORIZON;

export function calculateAlertSummaryMetrics(alerts: AlertItem[]): AlertSummaryMetrics {
  const activeAlerts = alerts.filter((a) => a.status !== 'resolved' && a.status !== 'dismissed');
  const criticalCount = activeAlerts.filter((a) => a.severity === 'CRITICAL').length;
  const warningCount = activeAlerts.filter((a) => a.severity === 'WARNING').length;
  const upcomingCount = alerts.filter((a) => a.severity === 'UPCOMING').length;
  const resolvedCount = alerts.filter((a) => a.status === 'resolved' || a.severity === 'RESOLVED').length;
  const unreadCount = alerts.filter((a) => a.status === 'unread').length;

  return {
    criticalCount,
    warningCount,
    upcomingCount,
    resolvedCount,
    unreadCount,
    trackedDomainsCount: 42,
    notificationDeliveryStatus: 'Configuration Only (Not Connected)',
  };
}
